### ISSUE TITLE
Complete Mobile Member UI wireframes

### ISSUE THREAD

**Issue by elliotmassen** [project-accelerate/accelerate#29]
The wireframes for Mobile Member UI need to be completed to include (at least) the "Create" sub-view and "Hosting" sub-view.

The "Create" sub-view should allow the logged-in user to create a new event. The "Hosting" sub-view should allow the logged-in user to view events that they have previous created.

This members area is for logged-in users who have permission to create events and will therefore display different sub-views to what a logged-in user without these permissions will see.

Acceptance criteria:
- Should include "Create" sub-view
- Should include "Hosting" sub-view

https://balsamiq.cloud/ssqd6/pd0rd/rB4C1

**Comment by pete-rossetti** [comment]
I will pick this up

**Comment by chrisdevereux** [comment]
Ah, memories.... 😢
